apiVersion: v1
kind: ConfigMap
metadata:
  name: templating
  annotations:
    kots.io/installer-only: "true"
data:
  # property-like keys; each key maps to a simple value
  distribution: repl{{ Distribution }}
  license_field: repl{{ LicenseFieldValue "plan" }}

  # file-like keys
#   game.properties: |
#     enemy.types=aliens,monsters
#     player.maximum-lives=5    
#   user-interface.properties: |
#     color.good=purple
#     color.bad=yellow
#     allow.textmode=true