apiVersion: embeddedcluster.replicated.com/v1beta1
kind: Config
spec:
  version: "2.2.0+k8s-1.29"
  domains:
    replicatedAppDomain: updates.alexparker.info
    proxyRegistryDomain: images.alexparker.info
  roles:
    controller:
      name: primary
      labels:
        primary: "true"
    custom:
    - name: database
      labels:
       database: "true"
  extensions:
    helm:
      repositories:
        - name: ingress-nginx
          url: https://kubernetes.github.io/ingress-nginx
      charts:
        - name: ingress-nginx
          chartname: ingress-nginx/ingress-nginx
          namespace: ingress-nginx
          version: "4.12.0"
          values: |
            controller:
              service:
                type: NodePort
                nodePorts:
                  http: "80"
                  https: "443"
              image:
                digest: ""
                digestChroot: ""
              admissionWebhooks:
                patch:
                  image:
                    digest: ""
