apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: gitea
spec:
  # chart identifies a matching chart from a .tgz
  chart:
    name: gitea
    chartVersion: 3.1.14
  values:
    service:
      type: NodePort
      nodePorts:
        http: 30005
      auth:
        username: repl{{ ConfigOption "postgres_username" }}
        password: repl{{ ConfigOption "postgres_password" }}
        database: repl{{ ConfigOption "postgres_database" }}
    replicated:
      isAirgap: repl{{ HasLocalRegistry }}
  optionalValues:
    - when: 'repl{{ HasLocalRegistry }}'
      values:
        image:
          registry: '{{repl LocalRegistryHost }}' 
          repository: '{{repl LocalRegistryNamespace }}/gitea'
        pullSecrets:
          - name: '{{repl ImagePullSecretName }}'
    - when: 'repl{{ HasLocalRegistry }}'
      values:
        postgresql:
          image:
            registry: '{{repl LocalRegistryHost }}'
            repository: '{{repl LocalRegistryNamespace }}/postgresql'
          pullSecrets:
            - name: '{{repl ImagePullSecretName }}'
    - when: 'repl{{ HasLocalRegistry }}'
      values:
        replicated:
          image:
            registry: '{{repl LocalRegistryHost }}'
            repository: '{{repl LocalRegistryNamespace }}/replicated-sdk'
          imagePullSecrets:
            - name: '{{repl ImagePullSecretName }}'
    - when: 'repl{{ ConfigOptionEquals "use_dedicated_pg_node" "1" }}'
      values:
        postgresql:
          primary:
            nodeSelector:
              database: "true"
  builder:
    global:
      replicated:
        dockerconfigjson: placeholder # don't fail air gap builds