apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: gitea-config
spec:
  groups:
  - name: gitea_settings
    title: Gitea Settings
    description: Settings for the Gitea application
    items:
    - name: gitea_username
      title: Gitea Username
      type: text
      required: true
    - name: gitea_password
      title: Gitea Password
      type: password
      required: true
    - name: gitea_email
      title: Gitea Admin Email
      type: text
      required: true
  - name: postgresql_settings
    title: PostgreSQL Settings
    items:
    - name: database_type
      title: Database Type
      type: select_one
      items:
      - name: embedded
        title: Embedded PostgreSQL
        description: Use the built-in PostgreSQL database (recommended for most deployments)
      - name: external
        title: External PostgreSQL
        description: Use an existing PostgreSQL database server
      default: embedded
      required: true
    - name: external_postgres_host
      title: External PostgreSQL Host
      type: text
      required: true
      help_text: The hostname and port of your external PostgreSQL server (e.g., "postgres.example.com:5432" or "10.0.0.100:5432")
      when: 'repl{{ ConfigOptionEquals "database_type" "external" }}'
    - name: external_postgres_database
      title: External PostgreSQL Database Name
      type: text
      default: gitea
      help_text: The name of the database to use for Gitea
      when: 'repl{{ ConfigOptionEquals "database_type" "external" }}'
    - name: external_postgres_username
      title: External PostgreSQL Username
      type: text
      required: true
      default: postgres
      help_text: The username to connect to the external PostgreSQL database
      when: 'repl{{ ConfigOptionEquals "database_type" "external" }}'
    - name: external_postgres_password
      title: External PostgreSQL Password
      type: password
      required: true
      help_text: The password to connect to the external PostgreSQL database
      when: 'repl{{ ConfigOptionEquals "database_type" "external" }}'
    - name: external_postgres_schema
      title: External PostgreSQL Schema
      type: text
      default: public
      help_text: The schema to use in the external PostgreSQL database
      when: 'repl{{ ConfigOptionEquals "database_type" "external" }}'
    - name: embedded_postgres_username
      title: Embedded PostgreSQL Username
      type: text
      default: gitea
      help_text: Username for the embedded PostgreSQL database
      when: 'repl{{ ConfigOptionEquals "database_type" "embedded" }}'
    - name: embedded_postgres_password
      title: Embedded PostgreSQL Password
      type: password
      default: gitea
      help_text: Password for the embedded PostgreSQL database
      when: 'repl{{ ConfigOptionEquals "database_type" "embedded" }}'
    - name: embedded_postgres_database
      title: Embedded PostgreSQL Database Name
      type: text
      default: gitea
      help_text: Database name for the embedded PostgreSQL database
      when: 'repl{{ ConfigOptionEquals "database_type" "embedded" }}'
    - name: enable_ha
      title: Enable High Availability
      type: bool
      default: false
      when: 'repl{{ ConfigOptionEquals "database_type" "embedded" }}'