apiVersion: troubleshoot.replicated.com/v1beta1
kind: Preflight
metadata:
  name: guestbook-preflight-checks
spec:
  analyzers:
    - clusterVersion:
        outcomes:
          - fail:
              when: "< 1.26.0"
              message: The application requires Kubernetes 1.26.0 or later, and recommends 1.27.0 or later.
              uri: https://www.kubernetes.io
          - warn:
              when: "< 1.27.0"
              message: Your cluster meets the minimum version of Kubernetes, but we recommend you update to 1.27.0 or later.
              uri: https://kubernetes.io
          - pass:
              message: Your cluster meets the recommended and required versions of Kubernetes.