name: Create Replicated Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      lint:
        description: 'Enable linting during release creation'
        required: false
        default: true
        type: boolean

env:
  REPLICATED_APP: gitea-mastodon
  REPLICATED_API_ORIGIN: https://api.replicated.com/vendor

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Get current version and generate semantic version
        id: version
        run: |
          # Get current version using Docker container with debug info
          echo "Getting current version from Unstable channel..."

          channel_output=$(docker run --rm \
            -e REPLICATED_API_TOKEN="${{ secrets.REPLICATED_API_TOKEN }}" \
            -e REPLICATED_APP="${{ env.REPLICATED_APP }}" \
            replicated/vendor-cli:latest \
            channel inspect 2Xob31FcCoAQdbHBn44NLHSgeZF --output json 2>&1)

          echo "Channel output: $channel_output"

          current_version=$(echo "$channel_output" | jq -r '.releaseLabel // empty' 2>/dev/null)
          echo "Current version parsed: '$current_version'"

          # Check if we got a valid version
          if [[ -z "$current_version" || "$current_version" == "null" ]]; then
            echo "ERROR: Could not get current version, using 1.0.0 as fallback"
            current_version="1.0.0"
          fi

          echo "Using current version: $current_version"

          # Check if current version follows semantic versioning (x.y.z format)
          if [[ $current_version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            # Parse and increment patch version
            IFS='.' read -r major minor patch <<< "$current_version"
            new_version="$major.$minor.$((patch + 1))"
            echo "Incrementing semantic version: $current_version -> $new_version"
          else
            # Current version is not semver, start with 1.0.0
            echo "Current version '$current_version' is not semantic, starting with 1.0.0"
            new_version="1.0.0"
          fi

          echo "New version: $new_version"
          echo "version=$new_version" >> $GITHUB_OUTPUT

      - name: Clean old Helm packages
        run: |
          if ls manifests/*.tgz >/dev/null 2>&1; then
            rm -f manifests/*.tgz
            echo "Cleaned old .tgz files"
          fi

      - name: Package Helm chart
        run: |
          helm package gitea -d manifests -u
          echo "Packaged Helm chart:"
          ls -la manifests/*.tgz

      - name: Create Replicated Release
        uses: docker://replicated/vendor-cli:latest
        with:
          args: release create --auto -y --version ${{ steps.version.outputs.version }}
        env:
          REPLICATED_API_TOKEN: ${{ secrets.REPLICATED_API_TOKEN }}
          REPLICATED_APP: ${{ env.REPLICATED_APP }}

      - name: Clean up artifacts
        if: always()
        run: |
          rm -f manifests/*.tgz
          echo "Cleaned up build artifacts"